=== w3c/wot/ucr-doc/ucr.dtd
<!ELEMENT ucr (usecase*, req*, tech*) >
 <!ELEMENT usecase (title, p*, ul?) >
 <!ATTLIST usecase
           id ID #REQUIRED
           author ( dret | stefan | joerg | h0ru5 | darko | mamund | inadarei | hlgr360 | cabo | daveraggett) #REQUIRED
           domain (home_automation | home_entertainment | home_secrity | sports_and_lifestyle | healthcare_and_medical | assisted_living | smart_grids | utility | transportation | emergency | retail | logistics | manufacturing | other) "other"
           >
 <!ELEMENT title (#PCDATA) >
 <!ELEMENT p ( #PCDATA | a )* >
 <!ELEMENT a (#PCDATA) >
 <!ATTLIST a
           href CDATA #REQUIRED
           title CDATA #REQUIRED
           >
 <!ELEMENT ol (li*) >
 <!ELEMENT ul (li*) >
 <!ELEMENT li (#PCDATA) >
 <!ATTLIST li
           reqref IDREF #REQUIRED >
 <!ELEMENT req (title, p*) >
 <!ATTLIST req
           id ID #REQUIRED
           type CDATA "functional"
           >
 <!ELEMENT tech (title, p*, ul?) >
 <!ATTLIST tech
           id ID #REQUIRED
           href CDATA #IMPLIED
           >

=== w3c/wot/ucr-doc/wot-ucr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="wot-ucr.xsl"?>
<!DOCTYPE ucr SYSTEM "ucr.dtd">
<ucr>
    <usecase id="building-automation" author="dret" domain="home_automation">
        <title>Building Automation</title>
        <p>Buildings often have a large variety of components such as Heating, Venting, and Air Conditioning (HVAC), lighting systems, and possibly more specialized systems such as support for reserving rooms electronically. Very often, these systems are not provided by a single supplier. Instead, landscapes of heterogeneous systems develop over time. Interoperability becomes a paramount challenge, as there should be a single way how interactions with the overall building automation infrastructure are possible. Furthermore, sensors, controllers, and actors of one system serving one specific use case can be useful for other use cases and can also enable new cross-domain applications and services to amplify comfort, security, and operational efficiency in smart buildings.</p>
        <p>Possibly, building automation scenarios can have layered services, such for example when it comes to temperature sensing. While the basic functionality of the building automation system might only include to get information about the current temperature in a variety of places, there also might be a "temperature history" service. This service might allow more advanced features such as accessing the complete history of temperature measurements, and possible even more advanced functionalities such as queries in this dataset. By combining available data (e.g., weather forcast and occupancy of meeting rooms), room temperatures and future cooling/heating demand can be predicted to increase (e.g., an office building's) energy efficiency. Again, such an advanced service should be accessible in the same way as the more basic services, so that developers can access all these services in a uniform way.</p>
        <ul>
            <li reqref="resource-description">Applications may want to get an understanding of what kind of sensors and other capabilities are exposed as part of the building automation system. In such a case, it is necessary that available resources can be described or are describing themselves, preferably using a framework that makes those descriptions uniform even if the underlying sensors or services are using different implementation and communication technologies.</li>
            <li reqref="push">Applications may want to be notified of certain events in the building automation system, without having to listen to a continuous event stream from it. In such a case, it is advantageous for the building automation system to support some kind of push mechanism, so that application can subscribe to these events, and will be notified when they happen. This increases the workload of the building automation system (it has to keep track of subscribers), but may make development of certain classes of applications much easier.</li>
        </ul>
    </usecase>
    <usecase id="bakery" author="stefan" domain="logistics">
        <title>Order Management System</title>
        <p>In companies like a large industry bakery you have storage facilities like silos to store production materials. In order to keep track of the amount of production material in the silos, level radar devices are used. The measurement data is collected by an order management system.</p>
        <p>As soon as the production material falls below a certain threshold, the system sends an order to a delivery company.</p>
        <ul>
            <li reqref="resource-description">At some point in the system, the measurement value has to be enriched with some meta-information (e.g., timestamp, unit, id, ...).</li>
            <li reqref="data-exchange-format">The bakery's order management has to interact with the order management system of the delivery company.</li>
            <li reqref="object-memory">For perishable ingredients like milk or cheese, the due date can be estimated much more precisely if an object memory is kept for them. Also it can be a way to prove the origin and freshness of ingridients</li>
            <li reqref="layered-comm">Given a commonality of interfacing protocols to heterogeneous ordering systems, layered communication enables a better reusability across several ordering systems. While the interaction primitives, transport protocol and representation might likely be the same for many systems, a difference in data structure demands a clear layering of the communication.</li>
        </ul>
    </usecase>
    <usecase id="adaptive-building" author="h0ru5" domain="home_automation">
        <title>Adaptive Building</title>
        <p>Each employee in an office building specifies a preference profile (temperature, light setup, table height, ...). Due to his company badge or his smartphone the building can automatically influence the building automation system around him based on his current location and preference profile.</p>
        <p>Besides an increase of comfort in general, personal profiles can also be used to assist people with special needs. For instance, in case of emergency, the acustic alarm sirens are insufficient for death people. Other mechanisms like flashing lights or mobile device notifications that are available in the person's proximity need to be used.</p>
        <p>In case of several people in the same room (e.g. a meeting), a meditation is needed. This is also the case in other cross-influenced situations and if overall goals are set to be achieved, such as energy saving.</p>
        <ul>
            <li reqref="ensemble-discovery">Dynamical selection of the surrounding/affecting resources to create the desired comfort level.</li>
            <li reqref="multi-stakeholder-operation">Multiple people in the same room require automatic mediation of desired comfort levels.</li>
            <li reqref="lifecycle-mgmt">The appearance and disappearance of users requires means to orchestrate the lifecycle of users/stakeholders.</li>
            <li reqref="resource-description">The environment around a user must be conceivable by the system in a way that does not require manual engineering.</li>
            <li reqref="privacy">Since the system would rely on informations which person  is in what room at what time, it can allow a very fine-grained movement profile, which is sensitve information</li>
            <li reqref="trust">The infrastructure has to secure personal profile information in order to prohibit unauthorized access or manipulation.</li>
        </ul>
    </usecase>
    <usecase id="shift-of-function" author="h0ru5" domain="manufacturing">
        <title>Shift of Function in Automation Systems</title>
        <p>In a factory, the automation function does not run on a large central system, but decision-making is increasingly decentralized, i.e., shifted "downwards" towards the machine or control panels on the shop flor. With the advent of the digitization, the demand for a flexible production in small batch sizes or the production of multi-variant mass products arises in many manufactoring industries. The production process can be adaptive if product memories specify the machining; appropriate paths along the production line can be discovered dynamically.</p>
        <p>In order to introduce such a new automation function, the function can first be run supervised inside the central system and then shifted downwards, e.g. installed on a field device.</p>
        <ul>
            <li reqref="embedded-runtime">A seamless shift of functions requires an embedded runtime which allows the simple implementation, monitoring and debugging of applications.</li>
            <li reqref="lifecycle-mgmt">The appearance and disappearance of devices as well as the software management on the devices itself requires means to orchestrate the lifecycle of individual devices resp. components.</li>
            <li reqref="resource-description">At some point in the system, the measurement value has to be enriched with some meta-information (e.g., timestamp, unit, id, ...).</li>
            <li reqref="layered-comm">In heterogeneous systems, the seamless shift of functionality requires a clear and consistent layering of application protocols since the functionality is focused on the data structure and should be agnostic of the underlying application layer protocol layers.</li>
            <!-- embedded is a must -->
        </ul>
    </usecase>
    <usecase id="vpp" author="h0ru5" domain="smart_grids">
        <title>Virtual Power Plants</title>
        <p>A Virtual Power Plant (VPP) is an aggregation of Distributed Energy Resources (DERs), that can act as an entity on energy markets or as an ancillary service to grid operation.</p>
        <p>The individual DERs often have a primary use on their own, with electric generation/consumption being a side-effect resp. secondary use. This results in negotiations/collaborations between many different parties e.g. such as the DER owner, the VPP operator, the grid operator and others.</p>
        <ul>
            <li reqref="multi-stakeholder-operation">Multiple involved parties have to find a common mode of operation</li>
            <li reqref="lifecycle-mgmt">Since the VPP is a dynamic system of loosely coupled DERs, the appearance and disappearance of DERs as well as the software management on the devices itself requires means to orchestrate the lifecycle of individual devices resp. components.</li>
            <li reqref="embedded-runtime">Especially for DERs in remote locations, maintaining a close couple control loop can be expensive if feasible at all. Therefore, it is desirable to be able to offload control logic to the DER itself.</li>
            <li reqref="ensemble-discovery">In order to dynamically find matching DERs needed for the operational goal of a VPP, a registry with different options of DER discovery is needed.</li>
